// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0bUK-1TkR5B5sDOwgfPjD6gQwA6mwHHw',
    appId: '1:800936933243:web:3c09b9b8484237f330efde',
    messagingSenderId: '800936933243',
    projectId: 'passon-ride-rental-888',
    authDomain: 'passon-ride-rental-888.firebaseapp.com',
    storageBucket: 'passon-ride-rental-888.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV_JlDJMTE3iumTB1rGlsIvuyePOL6wxk',
    appId: '1:800936933243:android:8d7a2ebd8544af6e30efde',
    messagingSenderId: '800936933243',
    projectId: 'passon-ride-rental-888',
    storageBucket: 'passon-ride-rental-888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJjtzseAoK-0RAQGsEW5fOpta2jBEFIzE',
    appId: '1:800936933243:ios:6a716d25dc384fdf30efde',
    messagingSenderId: '800936933243',
    projectId: 'passon-ride-rental-888',
    storageBucket: 'passon-ride-rental-888.firebasestorage.app',
    iosBundleId: 'com.PassionRide.app.PassionRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJjtzseAoK-0RAQGsEW5fOpta2jBEFIzE',
    appId: '1:800936933243:ios:6a716d25dc384fdf30efde',
    messagingSenderId: '800936933243',
    projectId: 'passon-ride-rental-888',
    storageBucket: 'passon-ride-rental-888.firebasestorage.app',
    iosBundleId: 'com.PassionRide.app.PassionRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0bUK-1TkR5B5sDOwgfPjD6gQwA6mwHHw',
    appId: '1:800936933243:web:34ca86a6f07c3c9f30efde',
    messagingSenderId: '800936933243',
    projectId: 'passon-ride-rental-888',
    authDomain: 'passon-ride-rental-888.firebaseapp.com',
    storageBucket: 'passon-ride-rental-888.firebasestorage.app',
  );
}
